import json
import time
from collections.abc import AsyncIterator

import httpx
import structlog

from app.domain.ports.llm import LLMPort

logger = structlog.get_logger(__name__)


class TritonLLMAdapter(LLMPort):
    """LLM adapter — calls qwen35_llm via vLLM /generate_stream on Triton.

    The model uses decoupled transaction policy, so /generate_stream is required.
    """

    def __init__(self, triton_url: str, system_prompt: str, max_tokens: int = 500) -> None:
        self._stream_url = f"http://{triton_url}/v2/models/qwen35_llm/generate_stream"
        self._system_prompt = system_prompt
        self._max_tokens = max_tokens
        self._client = httpx.AsyncClient(timeout=60.0)

    def _build_prompt(self, user_message: str) -> str:
        return (
            f"<|im_start|>system\n{self._system_prompt}<|im_end|>\n"
            f"<|im_start|>user\n{user_message} /no_think<|im_end|>\n"
            f"<|im_start|>assistant\n"
        )

    def _clean_token(self, token: str) -> str:
        """Strip residual chat template markers that vLLM may emit."""
        return token.replace("<|im_end|>", "").replace("<|im_start|>", "")

    async def stream_generate(self, message: str) -> AsyncIterator[str]:  # type: ignore[override]
        """Yield delta tokens as they are generated by the model."""
        log = logger.bind(message_len=len(message))
        log.debug("llm_stream_start")
        t0 = time.monotonic()
        token_count = 0
        in_think = False
        try:
            async with self._client.stream(
                "POST",
                self._stream_url,
                json={
                    "text_input": self._build_prompt(message),
                    "max_tokens": self._max_tokens,
                    "stream": True,
                    "stop": "<|im_end|>",
                },
            ) as resp:
                resp.raise_for_status()
                async for line in resp.aiter_lines():
                    if not line.startswith("data: "):
                        continue
                    try:
                        data = json.loads(line[6:])
                    except json.JSONDecodeError:
                        continue

                    token = self._clean_token(data.get("text_output", ""))
                    if not token:
                        continue

                    # Filter <think>...</think> blocks (Qwen thinking mode)
                    if "<think>" in token:
                        in_think = True
                    if in_think:
                        if "</think>" in token:
                            in_think = False
                        continue

                    token_count += 1
                    yield token
        except Exception as exc:
            log.error("llm_stream_error", duration_s=round(time.monotonic() - t0, 3), error=str(exc))
            raise

        log.info("llm_stream_complete", duration_s=round(time.monotonic() - t0, 3), tokens=token_count)

    async def generate(self, message: str) -> str:
        """Accumulate full stream response. Uses stream_generate internally."""
        tokens: list[str] = []
        async for token in self.stream_generate(message):
            tokens.append(token)
        return "".join(tokens).strip()

    async def aclose(self) -> None:
        await self._client.aclose()
